### ISSUE TITLE
The url has changed 

### ISSUE THREAD

**Issue by MahmoudAhmed8888** [keiyoushi/extensions-source#5343] opened 2024-10-03 14:22 UTC
### Source information

Keiyoushi

### Source language

Arabic 

### Source new URL

https://axztu.com/

### Other details

![Screenshot_٢٠٢٤-١٠-٠٣-١٧-٢٠-٤٥-٦٩_afd66b7916d19a60815f56273408b73e](https://github.com/user-attachments/assets/5ab81365-282d-4448-a94d-19ebfbf65b89)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-03 16:01
Duplicate of #5333

1) Source info means the extension's name and version number, not the repository's name

2) Search the existing issues before opening a new one, and acknowledging that you did when you didn't

**Closed** 2024-10-03 19:41 UTC
Labels: Bug, Domain changed
