### ISSUE TITLE
Can't read manga in colamanga

### ISSUE THREAD

**Issue by Narudesuu** [keiyoushi/extensions-source#4967] opened 2024-09-08 04:37 UTC
### Source information

Colamanga 1.4.18

### Source language

Chinese

### Steps to reproduce

Open source
Go any manga

### Expected behavior

Start read manga

### Actual behavior

Error
![Screenshot_20240908-123502~2](https://github.com/user-attachments/assets/2ac3137a-5812-4f03-9b8a-5dafcae319c6)

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-08 04:38
Duplicate of fixed #4942 

Update your extension

**Comment by Narudesuu** [comment] 2024-09-08 04:42
> Duplicate of fixed #4942
> 
> Update your extension

I can read now, thank you

**Closed** 2024-09-08 05:04 UTC
Labels: Bug
