### ISSUE TITLE
Asura Scans: NullPointerException when refreshing manga

### ISSUE THREAD

**Issue by pluto3210** [keiyoushi/extensions-source#5220] opened 2024-09-25 09:14 UTC
### Source information

Asura Scans 1.4.39

### Source language

English

### Steps to reproduce

1. Try to refresh manhwa from Asura Scans
2. 
![Screenshot_20240925-142347](https://github.com/user-attachments/assets/afe81382-cf24-4dcd-a5c0-ec3911fcb3a8)

### Expected behavior

Refreshed Chapters 

### Actual behavior

Error

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-25 09:15
Duplicate of #5198

Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't

**Closed as not planned** 2024-09-25 09:44 UTC
Labels: Bug
